---
# tasks file for logstash
- name: Copy logstash yum repo file
  copy:
    src=logstash.repo
    dest=/etc/yum.repos.d/logstash.repo
    owner=user
    group=user
    mode=0644
  become: true

- name: Install logstash rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - logstash

- name: Copy logstash input filters
  copy:
    src=02-beats-input.conf
    dest=/etc/logstash/conf.d/02-beats-input.conf
    owner=user
    group=user
    mode=0644
  become: true

- name: Copy logstash output filters
  copy:
    src=30-elasticsearch-output.conf
    dest=/etc/logstash/conf.d/30-lumberjack-output.conf
    owner=user
    group=user
    mode=0644
  become: true

