---
# tasks file for logstash
- name: Copy logstash yum repo file
  copy:
    src=logstash.repo
    dest=/etc/yum.repos.d/logstash.repo
    owner=user
    group=user
    mode=0644
  become: true

- name: Install logstash rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - logstash

- name: Copy logstash input filters
  copy:
    src=02-beats-input.conf
    dest=/etc/logstash/conf.d/02-beats-input.conf
    owner=user
    group=user
    mode=0644
  become: true

- name: Copy logstash output filters
  copy:
    src=30-elasticsearch-output.conf
    dest=/etc/logstash/conf.d/30-elasticsearch-output.conf
    owner=user
    group=user
    mode=0644
  become: true

- name: Copy logstash syslog filters
  copy:
    src=10-syslog-filter.conf
    dest=/etc/logstash/conf.d/10-syslog-filter.conf
    owner=user
    group=user
    mode=0644
  become: true

- name: Copy logstash chef logs filter
  copy:
    src=13-chef-central-log.conf
    dest=/etc/logstash/conf.d/13-chef-central-log.conf
    owner=user
    group=user
    mode=0644
  become: true
  register: logstash_needs_restart

- name: Copy logstash apachelog filter
  copy:
    src=11-apachelog-filter.conf
    dest=/etc/logstash/conf.d/11-apachelog-filter.conf
    owner=user
    group=user
    mode=0644
  become: true
  register: logstash_needs_restart

