---

- name: Copying logstash repo
  template: src=ansible-elk/files/logstash.repo.j2 dest=/etc/yum.repos.d/logstash.repo

- name: Install Logstash
  yum: name=logstash state=installed

- name: Generate SSL certificates
  include: generate-ssl.yml

- name: Configure Logstash input
  copy: src=ansible-elk/files/02-beats-input.conf dest=/etc/logstash/conf.d/02-beats-input.conf

- name: Configure Http input
  copy: src=ansible-elk/files/03-http-input.conf dest=/etc/logstash/conf.d/03-http-input.conf

- name: Configure Http filter
  copy: src=ansible-elk/files/14-http-filter.conf dest=/etc/logstash/conf.d/14-http-filter.conf

- name: Configure Logstash apache-log filter
  copy: src=ansible-elk/files/11-apache-logs-filter.conf dest=/etc/logstash/conf.d/11-apache-logs-filter.conf

- name: Configure Logstash chef-logs filter
  copy: src=ansible-elk/files/12-chef-logs.conf dest=/etc/logstash/conf.d/12-chef-logs.conf

- name: Configure Logstash chef-logs-central filter
  copy: src=ansible-elk/files/13-chef-central-logs.conf dest=/etc/logstash/conf.d/13-chef-central-logs.conf

- name: Configure Logstash syslog filter
  copy: src=ansible-elk/files/10-syslog-filter.conf dest=/etc/logstash/conf.d/10-syslog-filter.conf

- name: Configure Logstash ouput
  copy: src=ansible-elk/files/30-elasticsearch-output.conf dest=/etc/logstash/conf.d/30-elasticsearch-output.conf

- name: Restart Logstash
  service: name=logstash state=restarted
