---
# tasks file for elasticsearch
- name: Copy elasticsearch yum repo file
  copy:
    src=elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Install elasticsearch and openjdk
  yum: name={{ item }} state=present
  become: true
  with_items:
    - elasticsearch
    - java-openjdk-headless

- name: Edit the config file for localhost
  lineinfile:
    dest='/etc/elasticsearch/elasticsearch.yml'
    line=" network.host{{':'}} localhost"

- name: Start elasticsearch service
  command: service elasticsearch start
  ignore_errors: true

- name: Setup elasticsearch service
  service: name=elasticsearch state=started enabled=true
  become: true
